version: '3.8'
services:
  db:
    container_name: pg
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_SSL=disable
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - db
volumes:
  db:
    driver: local