version: "3.8"
services:
  db:
    container_name: pg
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSL=disable
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - db
volumes:
  db:
    driver: local
